version: '3'
dotenv:
  - ./database/.dec.env
vars:
  MICROMAMBA_ENV: security
  MICROMAMBA_FILE: '{{.MICROMAMBA_ENV}}.env.yaml'
tasks:
  env:set:
    sources:
      - '{{.MICROMAMBA_FILE}}'
      - requirements.txt
    cmd: micromamba create -f '{{.MICROMAMBA_FILE}}' -y
  setup:
    dir: ./database/
    cmd: docker compose up -d
  run:app:
    deps:
      - env:set
    cmd: micromamba -n '{{.MICROMAMBA_ENV}}' run python main.py
  decrypt:
    dir: ./database
    sources:
      - .enc.env
    generates:
      - .dec.env
    cmd: sops -d .enc.env > .dec.env
  sops:install:
    cmds:
      - curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
      - sudo mv sops-v3.8.1.linux.amd64 /usr/local/bin/sops
      - sudo chmod +x /usr/local/bin/sops
